### PR TITLE
Fix searching for SDKs when a `--triple` is specified along with the SDK name

### LINKED ISSUE #7973: `--swift-sdk` option cannot uniquely select a Swift SDK
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

A Swift SDK can be identified by a combination of an artifact ID and a target triple by its definition. However, the current Swift SDK selector accepted by the `--swift-sdk` flag only allows specifying either an artifact ID or a target triple, making it impossible to uniquely select the desired Swift SDK in the following situation:

A developer installs two Artifacts containing two Swift SDKs with target triples A and B respectively:

```
~/.config/swiftpm/swift-sdks
├── swift-DEVELOPMENT-SNAPSHOT-2024-06-13-a_static-linux-0.0.1.artifactbundle
│   └── swift-DEVELOPMENT-SNAPSHOT-2024-06-13-a_static-linux-0.0.1/swift-linux-musl/musl-1.2.5.sdk
│       ├── aarch64
│       └── x86_64
└── swift-DEVELOPMENT-SNAPSHOT-2024-07-02-a_static-linux-0.0.1.artifactbundle
    └── swift-DEVELOPMENT-SNAPSHOT-2024-07-02-a_static-linux-0.0.1/swift-linux-musl/musl-1.2.5.sdk
        ├── aarch64
        └── x86_64
```

Then there are 4 Swift SDKs for:
- Swift SDK A: `swift-DEVELOPMENT-SNAPSHOT-2024-06-13-a_static-linux-0.0.1` (target: `aarch64-swift-linux-musl`)
- Swift SDK B: `swift-DEVELOPMENT-SNAPSHOT-2024-06-13-a_static-linux-0.0.1` (target: `x86_64-swift-linux-musl`)
- Swift SDK C: `swift-DEVELOPMENT-SNAPSHOT-2024-07-02-a_static-linux-0.0.1` (target: `aarch64-swift-linux-musl`)
- Swift SDK D: `swift-DEVELOPMENT-SNAPSHOT-2024-07-02-a_static-linux-0.0.1` (target: `x86_64-swift-linux-musl`)

If a developer specifies `swift build --swift-sdk x86_64-swift-linux-musl`, there are two candidates (Swift SDK B and D)
If a developer specifies `swift build --swift-sdk swift-DEVELOPMENT-SNAPSHOT-2024-07-02-a_static-linux-0.0.1`, there are still two candidates (Swift SDK C and D)

### Potential Solutions

I think we have two options to allow a developer to specify the combination of an Artifact ID and a target triple:
1. Use value specified by `--triple` option if specified with `--swift-sdk` (Currently, `--swift-sdk` and `--triple` are both specified, `--triple` option is preferred, and `--swift-sdk` is just ignored.)
    - Pros: No new option
    - Cons: It's a little bit confusing because `--swift-sdk` does not identify a Swift SDK but just identify an Artifact containing Swift SDKs.
2. Extend the Swift SDK selector expression to allow specifying the both. e.g. `--swift-sdk swift-DEVELOPMENT-SNAPSHOT-2024-07-02-a_static-linux-0.0.1:x86_64-swift-linux-musl`
    -  Pros: `--swift-sdk` identifies a Swift SDK clearly
    - Cons: As we don't limit the character set of an artifact ID, so not sure if we can interpret the selector expression without ambiguity
3. Assign Swift SDK ID to each SDK that are independent from artifact ID
4. Restrict an artifact to have only a single Swift SDK

### Swift Package Manager version/commit hash

da65429043cb0a5151bdd5e9666df770dfbc72a5

### PR DESCRIPTION
**Pull request by finagolfin**
Extend `selectBundle()` to use the existing `selectSwiftSDK(id:hostTriple:targetTriple)` overload, plus fix the latter to check the full triple string, which affects `swift sdk configure` also.

Fixes https://github.com/swiftlang/swift-package-manager/issues/7973 and https://github.com/swiftlang/swift-package-manager/issues/9220

Spun off from #9229, ~I'll~ added some tests ~and~ to get this in.

### CODE REVIEW

**Comment by owenv** [comment]
thanks, this lgtm once we have some basic testing in place

File: Tests/CommandsTests/SwiftSDKCommandTests.swift [hunk 1]
```diff
@@ -295,6 +295,16 @@ struct SwiftSDKCommandTests {
...
 
+            let invocation =
+                [   "configure", "--show-configuration",
+                    "--swift-sdks-path", fixturePath.pathString,
+                    "test-artifact",
+                    "aarch64-unknown-linux-gnu11.0",
+                ]
+            (stdout, stderr) = try await command.execute(invocation)
+
+            #expect(stderr.contains("and target triple aarch64-unknown-linux-gnu11.0 is not currently installed.")
```
Comment (finagolfin) [inline Tests/CommandsTests/SwiftSDKCommandTests.swift]: In my testing with this command and Swift 6.3, it would incorrectly match and show the bundle output above, rather than erroring like this. Not too important in 6.3, as `swift sdk configure` currently does nothing to affect compilation, ie #8958, but it will be as we get that command fixed in #9229.

**Comment by finagolfin** [comment]
@swift-ci test

**Comment by finagolfin** [comment]
@swift-ci test linux

**Comment by finagolfin** [comment]
@swift-ci test macOS

**Review by owenv — APPROVED** [review]

**Comment by finagolfin** [comment]
@swift-ci test windows

**Comment by finagolfin** [comment]
@swift-ci smoke test macOS

**Comment by finagolfin** [comment]
@swift-ci test macOS

**Comment by finagolfin** [comment]
@swift-ci test windows

**Review by jakepetroules — APPROVED** [review]

**Comment by jakepetroules** [comment]
@swift-ci test windows

**Comment by finagolfin** [comment]
[Sourcekit-lsp tests are failing](https://ci-external.swift.org/job/swiftpm-PR-windows/15648/) on all these Windows PR CI right now, [here's a previous CI run for an unrelated pull](https://ci-external.swift.org/job/swiftpm-PR-windows/15646/console) that also failed running them.

**Comment by finagolfin** [comment]
Hmm, I see other Windows CI runs passing with the same trunk sourcekit-lsp commit, so either this is a flaky test or some underlying dependency change is causing the failure instead, trying again.

@swift-ci test windows

**Comment by finagolfin** [comment]
Failed again on Windows PR CI, [as are all recent pulls](https://ci-external.swift.org/job/swiftpm-PR-windows/15663/console), may be a changed dependency like the compiler causing it.

**Comment by finagolfin** [comment]
Yep, Rintaro looking into it, swiftlang/sourcekit-lsp#2614.

**Comment by finagolfin** [comment]
@swift-ci test windows
