### PR TITLE
Fix `swift test --xunit-output=output.xml`

### LINKED ISSUE #9960: `swift test --xunit-output` inconsistent behavior with and without `=`
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [x] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

`swift test --xunit-output example.xml` differs from `swift test --xunit-output=example.xml`; one generates output in `example-swift-testing.xml`, and the other generates output in `example.xml`.

### Expected behavior

`swift test --xunit-output example.xml` and `swift test --xunit-output=example.xml` should do the same thing.

It might well make sense to have a separate `example-swift-testing.xml` file in projects that mix XCTest and Swift Testing  tests, but in projects with just Swift Testing, `--xunit-output example.xml` should just put its output in `example.xml`

### Actual behavior

* `swift test --xunit-output example.xml` generates output in `example-swift-testing.xml`
* `swift test --xunit-output=example.xml` generates output in `example.xml`

### Steps to reproduce

```
% rm -rf example
% mkdir example
% cd example
% swift package init
% swift test --xunit-output example.xml
Build complete! (1.82s)
Test Suite 'All tests' started at 2026-04-19 12:02:24.419.
Test Suite 'All tests' passed at 2026-04-19 12:02:24.419.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
􀟈  Test run started.
􀄵  Testing Library Version: 1743
􀄵  Target Platform: arm64e-apple-macos14.0
􀟈  Test example() started.
􁁛  Test example() passed after 0.001 seconds.
􁁛  Test run with 1 test in 0 suites passed after 0.001 seconds.
% cat example.xml
cat: example.xml: No such file or directory
% ls *.xml
example-swift-testing.xml
% cat example-swift-testing.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="TestResults" errors="0" tests="1" failures="0" skipped="0" time="0.000244708">
    <testcase classname="exampleTests" name="example()" time="0.000103791" />
  </testsuite>
</testsuites>
```

Then try it again with `=`:

```
% rm -f "*.xml"
% swift test --xunit-output=example.xml
Building for debugging...
[1/1] Write swift-version--58304C5D6DBC2206.txt
Build complete! (0.07s)
Test Suite 'All tests' started at 2026-04-19 12:11:27.478.
Test Suite 'All tests' passed at 2026-04-19 12:11:27.479.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
􀟈  Test run started.
􀄵  Testing Library Version: 1743
􀄵  Target Platform: arm64e-apple-macos14.0
􀟈  Test example() started.
􁁛  Test example() passed after 0.001 seconds.
􁁛  Test run with 1 test in 0 suites passed after 0.001 seconds.
% cat example-swift-testing.xml
cat: example-swift-testing.xml: No such file or directory
% cat example.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="TestResults" errors="0" tests="1" failures="0" skipped="0" time="0.000231541">
    <testcase classname="exampleTests" name="example()" time="8.4375e-05" />
  </testsuite>
</testsuites>
```

### Swift Package Manager version/commit hash

swift-driver version: 1.148.6 Apple Swift version 6.3.1 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)

### Swift & OS version (output of `swift --version ; uname -a`)

```
% swift --version; uname -a
swift-driver version: 1.148.6 Apple Swift version 6.3.1 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)
Target: arm64-apple-macosx26.0
Darwin MacBook-Pro.local 25.4.0 Darwin Kernel Version 25.4.0: Thu Mar 19 19:33:50 PDT 2026; root:xnu-12377.101.15~1/RELEASE_ARM64_T6050 arm64
```

### PR DESCRIPTION
**Pull request by dfabulich**
Fixes #9960

Fix `swift test --xunit-output=output.xml` (which incorrectly behaved differently from `swift test --xunit-output output.xml` with no equals sign)

### Motivation:

I lost hours trying to figure out why my XCTest xunit output was missing. #9960 was the reason why; this one-liner PR fixes it.

### Modifications:

`SwiftTestCommand.swift` had code to strip `--xunit-output` from the output arguments, but it considered only the two-argument form `--xunit-output output.xml`. It both didn't _append_ the argument, and it skipped the following argument.

I added a one-line fix (with an additional line of comment) to also skip the one-argument form `--xunit-output=output.xml`

### Result:

Now, `--xunit-output=output.xml` will behave exactly the same as `--xunit-output output.xml`. In `--parallel` mode, `swift test` will generate an `output.xml` file for XCTest results and a separate `output-swift-testing.xml` for Swift Testing results.

### CODE REVIEW

**Comment by plemarquand** [comment]
@swift-ci test

File: Sources/Commands/SwiftTestCommand.swift [hunk 1]
```diff
@@ -575,6 +575,8 @@ public struct SwiftTestCommand: AsyncSwiftCommand {
             while let arg = originalCommandLineArguments.next() {
                 if arg == "--xunit-output" {
                     _ = originalCommandLineArguments.next()
+                } else if arg.hasPrefix("--xunit-output=") {
+                    // Drop the combined form so it is not passed through in addition to SPM's `--xunit-output`.
```
[the remark this answers is not in the document]
Comment (dfabulich) [reply Sources/Commands/SwiftTestCommand.swift:579]: I added a test.

[the remark this answers is not in the document]
Comment (plemarquand) [reply Sources/Commands/SwiftTestCommand.swift:579]: Thanks, and also my apologies, I accidentally hit the copilot review button when starting CI. Still a worthy fix, I just prefer to review myself.

File: Tests/CommandsTests/TestCommandTests.swift [hunk 2]
```diff
@@ -539,6 +539,66 @@ struct TestCommandTests {
...
+    /// overwrites the XCTest JUnit file. See discussion in swift-package-manager around combined forms.
+    @Test(
+        .tags(
+            .Feature.TargetType.Executable,
+            .Feature.CommandLineArguments.TestParallel,
+            .Feature.CommandLineArguments.TestOutputXunit,
+            .Feature.CommandLineArguments.TestEnableXCTest,
+            .Feature.CommandLineArguments.TestEnableSwiftTesting,
+        ),
+        .issue("https://github.com/swiftlang/swift-package-manager/issues/8479", relationship: .defect),
```
Comment (bkhouri) [inline Tests/CommandsTests/TestCommandTests.swift]: issue (blocking): the issue URL is unrelated to this test.

Comment (bkhouri) [inline Tests/CommandsTests/TestCommandTests.swift]: Can we add the issue this PR fixes as a trait?  something like the following 
```suggestion
        .issue("https://github.com/swiftlang/swift-package-manager/issues/8479", relationship: .defect),
        .issue("https://github.com/swiftlang/swift-package-manager/issues/9960", relationship: .verifies),

```

File: Tests/CommandsTests/TestCommandTests.swift [hunk 3]
```diff
@@ -539,6 +539,66 @@ struct TestCommandTests {
...
+        .SWBINTTODO("Result XML could not be found. The build fails because of missing test helper generation logic for non-macOS platforms"),
+        arguments: SupportedBuildSystemOnAllPlatforms.filter { $0 != .xcode },
+    )
+    func swiftTestParallelXunitOutputCombinedEqualsForm(
+        buildSystem: BuildSystemProvider.Kind,
+    ) async throws {
+        let configuration = BuildConfiguration.debug
+        try await withKnownIssue(isIntermittent: true) {
```
Comment (bkhouri) [inline Tests/CommandsTests/TestCommandTests.swift]: issue (blocking): We should add a `.issue(url:relationship)` custom trait to this test which tracks the issue.

Do you have a sample of the failure that is occurring on Windows? 
- if not, could you get one so we can potentially help with the issue number. 
- if so, can you either add a custom `.issue()` trait, or share the failure so we can help determine which traits to add.


See https://github.com/swiftlang/swift-package-manager/blob/main/Sources/_InternalTestSupport/SwiftTesting%2BTraitsBug.swift for existing custom traits.  Feel free to expand it too.

File: Tests/CommandsTests/TestCommandTests.swift [hunk 4]
```diff
@@ -539,6 +539,66 @@ struct TestCommandTests {
...
+    @Test(
+        .tags(
+            .Feature.TargetType.Executable,
+            .Feature.CommandLineArguments.TestParallel,
+            .Feature.CommandLineArguments.TestOutputXunit,
+            .Feature.CommandLineArguments.TestEnableXCTest,
+            .Feature.CommandLineArguments.TestEnableSwiftTesting,
+        ),
+        .issue("https://github.com/swiftlang/swift-package-manager/issues/8479", relationship: .defect),
+        .SWBINTTODO("Result XML could not be found. The build fails because of missing test helper generation logic for non-macOS platforms"),
```
Comment (bkhouri) [inline Tests/CommandsTests/TestCommandTests.swift]: question: is this still an issue? can we remove it if not?

**Review by bkhouri — COMMENTED** [review]
Thank you very much for this. Could I just ask you to make some changes/improvements?

**Comment by dfabulich** [comment]
@bkhouri All of of your comments are on the test, which I copied and pasted. I'm unable to answer any questions you may have about why the test has these comments/markers, but I can certainly remove them.

File: Tests/CommandsTests/TestCommandTests.swift (hunk 4 above)
Comment (dfabulich) [reply Tests/CommandsTests/TestCommandTests.swift]: I copied and pasted this; I've removed it

File: Tests/CommandsTests/TestCommandTests.swift (hunk 3 above)
Comment (dfabulich) [reply Tests/CommandsTests/TestCommandTests.swift]: I copied and pasted this; I've removed it

**Comment by bkhouri** [comment]
> @bkhouri All of of your comments are on the test, which I copied and pasted. I'm unable to answer any questions you may have about why the test has these comments/markers, but I can certainly remove them.

Thanks for the update.  it looks good.

**Review by bkhouri — APPROVED** [review]

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

File: Tests/CommandsTests/TestCommandTests.swift (hunk 3 above)
Comment (dfabulich) [reply Tests/CommandsTests/TestCommandTests.swift]: I guess we have a sample of the failure now that the Windows CI has failed.

<details><summary>Windows CI failure log</summary>
<p>

```
[2026-04-22T18:26:32.112Z] × Test swiftTestParallelXunitOutputCombinedEqualsForm(buildSystem:) recorded an issue with 1 argument buildSystem → .swiftbuild at TestCommandTests.swift:545:6: Caught error: terminated(1): C:\source\swiftpm\.test\out\Products\Debug-windows\swift-test --package-path C:\Users\ContainerAdministrator\AppData\Local\Temp\DefaultInteropMode.BnYmom\DefaultInteropMode --configuration debug --build-system swiftbuild --parallel --enable-xctest --enable-swift-testing --xunit-output=C:\Users\ContainerAdministrator\AppData\Local\Temp\DefaultInteropMode.BnYmom\DefaultInteropMode\output.xml output:

[2026-04-22T18:26:32.112Z]     Building for debugging...

[2026-04-22T18:26:32.112Z]     Computing dependencies

[2026-04-22T18:26:32.112Z]     Constructing description

[2026-04-22T18:26:32.112Z]     Pre-planning 1 / 66

[2026-04-22T18:26:32.112Z]     Planning 1 / 66

[2026-04-22T18:26:32.112Z]     Planning deferred tasks

[2026-04-22T18:26:32.112Z]     Creating build graph

[2026-04-22T18:26:32.112Z]     Constructing 1 / 137

[2026-04-22T18:26:32.112Z]     [33/100] DefaultInteropModeTests-test-runner 11 / 32

[2026-04-22T18:26:32.112Z]     [60/100] DefaultInteropModeTests-product 20 / 33

[2026-04-22T18:26:32.112Z]     [58/100] DefaultInteropModeTests-product 20 / 34

[2026-04-22T18:26:32.112Z]     [62/100] DefaultInteropModeTests-product 23 / 36

[2026-04-22T18:26:32.112Z]     [72/100] DefaultInteropModeTests-product 27 / 36

[2026-04-22T18:26:32.112Z]     [72/100] DefaultInteropModeTests-product 27 / 37

[2026-04-22T18:26:32.112Z]     [75/100] DefaultInteropModeTests-product 28 / 37

[2026-04-22T18:26:32.112Z]     [81/100] DefaultInteropModeTests-product 30 / 37

[2026-04-22T18:26:32.112Z]     [83/100] DefaultInteropModeTests-test-runner 31 / 37

[2026-04-22T18:26:32.112Z]     [84/100] DefaultInteropModeTests-test-runner 32 / 38

[2026-04-22T18:26:32.112Z]     [82/100] DefaultInteropModeTests-test-runner 32 / 39

[2026-04-22T18:26:32.112Z]     [84/100] DefaultInteropModeTests-test-runner 34 / 40

[2026-04-22T18:26:32.112Z]     [93/100] DefaultInteropModeTests-test-runner 39 / 41

[2026-04-22T18:26:32.112Z]     error: FileSystemError(kind: TSCBasic.FileSystemError.Kind.noEntry, path: Optional(<AbsolutePath:"C:\Users\ContainerAdministrator\AppData\Local\Temp\DefaultInteropMode.BnYmom\DefaultInteropMode\.build\out\Intermediates.noindex\DefaultInteropMode.build\Debug-windows\DefaultInteropModeTests-test-runner.build\Objects-normal\x86_64\DefaultInteropModeTests-test-runner.LinkFileList">))

[2026-04-22T18:26:32.112Z]     error: Ld C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\DefaultInteropMode.BnYmom\\DefaultInteropMode\\.build\\out\\Products\\Debug-windows\\DefaultInteropModeTests-test-runner.exe normal failed with a nonzero exit code. Command line:     cd C:\Users\ContainerAdministrator\AppData\Local\Temp\DefaultInteropMode.BnYmom\DefaultInteropMode

[2026-04-22T18:26:32.112Z]         C:\Users\ContainerAdministrator\AppData\Local\Programs\Swift\Toolchains\6.2.0+Asserts\usr\bin\swiftc.exe -target x86_64-unknown-windows-msvc -emit-executable -sdk C:\Users\ContainerAdministrator\AppData\Local\Programs\Swift\Platforms\6.2.0\Windows.platform\Developer\SDKs\Windows.sdk -LC:\Users\ContainerAdministrator\AppData\Local\Temp\DefaultInteropMode.BnYmom\DefaultInteropMode\.build\out\Intermediates.noindex\EagerLinkingTBDs\Debug-windows -LC:\Users\ContainerAdministrator\AppData\Local\Temp\DefaultInteropMode.BnYmom\DefaultInteropMode\.build\out\Products\Debug-windows -LC:\Users\ContainerAdministrator\AppData\Local\Programs\Swift\Platforms\6.2.0\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\windows\x86_64 -LC:\Users\ContainerAdministrator\AppData\Local\Programs\Swift\Platforms\6.2.0\Windows.platform\Developer\Library\Testing-6.2.0\usr\lib\swift\windows -LC:\Users\ContainerAdministrator\AppData\Local\Programs\Swift\Platforms\6.2.0\Windows.platform\Developer\Library\Testing-6.2.0\usr\lib\swift\windows\x86_64 -LC:\Users\ContainerAdministrator\AppData\Local\Programs\Swift\Platforms\6.2.0\Windows.platform\Developer\Library\XCTest-6.2.0\usr\lib\swift\windows\x86_64 -LC:\Users\ContainerAdministrator\AppData\Local\Programs\Swift\Platforms\6.2.0\Windows.platform\Developer\Library\XCTest-6.2.0\usr\lib\swift\windows @C:\Users\ContainerAdministrator\AppData\Local\Temp\DefaultInteropMode.BnYmom\DefaultInteropMode\.build\out\Intermediates.noindex\DefaultInteropMode.build\Debug-windows\DefaultInteropModeTests-test-runner.build\Objects-normal\x86_64\DefaultInteropModeTests-test-runner.LinkFileList -Xlinker /OPT:REF -LC:\Users\ContainerAdministrator\AppData\Local\Programs\Swift\Toolchains\6.2.0+Asserts\usr\lib\swift -L/usr/lib/swift -use-ld=lld-link -Xlinker -debug:dwarf -lDefaultInteropModeTests -o C:\Users\ContainerAdministrator\AppData\Local\Temp\DefaultInteropMode.BnYmom\DefaultInteropMode\.build\out\Products\Debug-windows\DefaultInteropModeTests-test-runner.exe

[2026-04-22T18:26:32.112Z]     error: Build failed

[2026-04-22T18:26:32.112Z]     error: fatalError

[2026-04-22T18:26:32.112Z] 

[2026-04-22T18:26:32.112Z] × Test swiftTestParallelXunitOutputCombinedEqualsForm(buildSystem:) with 2 test cases failed after 92.687 seconds with 1 issue.
```

</p>
</details> 

I don't know anything about this, and it's out of scope for me to investigate it. The log is totally incomprehensible to me, and I don't have a Windows machine on which to reproduce it.

It's got some kinda FileSystemError, trying to read a file that I don't recognize `DefaultInteropModeTests-test-runner.LinkFileList`. What does that mean? I don't even think this log is clear enough to file a new issue based on it.

There are 8 tests in `TestCommandTests.swift` that are tagged with https://github.com/swiftlang/swift-package-manager/issues/8479, including `swiftTestParallel_ParallelArgumentWithXunitOutputGeneration`, the test that I copied and pasted it make this test, `swiftTestParallelXunitOutputCombinedEqualsForm`.

* https://github.com/swiftlang/swift-package-manager/issues/8479

The only thing clear to me is that this test doesn't work correctly on Windows. It's not at all clear to me whether https://github.com/swiftlang/swift-package-manager/issues/8479 is the root cause of the CI failure we see here, and I see no way forward for me to investigate that question.

So! I have two alternative proposals to move forward:

1. I could bring back `withKnownIssue(isIntermittent: true)` `when: { ProcessInfo.hostOperatingSystem == .windows }` _without_ filing an issue, as I did when I initially copied and pasted this test.
2. Alternately if @bkhouri or anyone else on your team can make any sense of this failure, I invite you to file an issue on it. If you file an issue, I'll update my PR to link to it.

What do you suggest?

Comment (daveinglis) [reply Tests/CommandsTests/TestCommandTests.swift]: you will need to add the `withKnownIssue(isIntermittent: true)`, until we start using newer sdks in our pipelines, you may notice other tests that have comments/issues around failures due to long paths on windows, you can just do the same here.

**Comment by plemarquand** [comment]
@swift-ci test windows platform

File: Tests/CommandsTests/TestCommandTests.swift (hunk 3 above)
Comment (dfabulich) [reply Tests/CommandsTests/TestCommandTests.swift]: Long file names was the hint I needed. I filed #9982 and updated the test to link to #9982, re-adding `withKnownIssue`.

**Comment by dfabulich** [comment]
@swift-ci test windows platform

**Comment by dfabulich** [comment]
I don't think swift-ci listens to my requests. Can somebody else run it?

**Comment by daveinglis** [comment]
@swift-ci test

**Comment by daveinglis** [comment]
@swift-ci test windows

**Comment by dfabulich** [comment]
I don't understand that CI failure. It looks like something cancelled the build…? there's no test failure or compile failure that I can see. cmake failed, but… why?

**Comment by daveinglis** [comment]
@swift-ci test windows

**Comment by dfabulich** [comment]
🎉 CI's green!

**Comment by bkhouri** [comment]
Thank you @dfabulich for this contribution.
