### PR TITLE
Include out-of-target resources

### LINKED ISSUE #6982: Unable To Copy Files Outside Of Target Source Folder
### Description

When constructing a package which may have targets which rely on vendored files (say a `.lib` or `.h` created by an external build system) it would be reasonable to create some kind of `vendor` folder at the root of the package and then use the `.copy` command to specify which resources need to be pulled into which targets, something similar to the following:
CleanShot 2023-10-09 at 17 32 29@2x

In this setup Swift PM silently fails to copy files within the package root but outside of the target's source folder.

### Expected behavior

I would expect the files to be copied into a bundle under the `.build` folder which does happen successfully if you `.copy` a file within the target's source folder. This would allow people to construct arbitrary bundles that help meet the needs of the software they are building.

### Actual behavior

Swift PM silently fails to copy any files referenced that are outside of the target's source folder.

### Steps to reproduce

1. Run `swift build` on the sample project attached
2. Open up the `.build/debug` folder
3. Look at the contents of `TestCopy_App.bundle` 

Notice there is only 1 file there, while 3 valid file paths have been specified in the Package file.

[TestCopy.zip](https://github.com/apple/swift-package-manager/files/12850799/TestCopy.zip)

### Swift Package Manager version/commit hash

_No response_

### Swift & OS version (output of `swift --version ; uname -a`)

Target: arm64-apple-macosx14.0
Darwin zerocool.localdomain 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

This also happens on the latest Swift on Windows toolchain as well.

### PR DESCRIPTION
**Pull request by neonichu**
It is possible to declare references to resources outside of ones target and it doesn't seem like that should be problematic in any way. Currently, these declarations essentially get ignored because the algorithm looks at files inside the target and applies rules to them, so any unmatched rules simply get ignored. In the grand scheme of things it may make sense to change that approach in a more fundamental way, but to fix this particular problem we can simply record all rules that were used and apply the unmatched rules after that initial processing has finished. Since this is a significant behavior change, we only do it for tools-version 5.11 or later.

rdar://119040426
resolves #6982

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Interesting, looks like the new test fails specifically on Linux?

```
Test Case 'ResourcesTests.testResourcesOutsideOfTargetCanBeIncluded' started at 2024-01-05 21:30:21.118
/home/build-user/swiftpm/Tests/FunctionalTests/ResourcesTests.swift:169: error: ResourcesTests.testResourcesOutsideOfTargetCanBeIncluded : XCTAssertTrue failed - resource file wasn't copied by the build
<EXPR>:0: error: ResourcesTests.testResourcesOutsideOfTargetCanBeIncluded : threw error "Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory""
Test Case 'ResourcesTests.testResourcesOutsideOfTargetCanBeIncluded' failed (4.135 seconds)
```

**Comment by neonichu** [comment]
Ah we generate "MyPackage_exec.resources" instead of a `.bundle` on Linux, it seems.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test windows

File: Sources/PackageLoading/TargetSourcesBuilder.swift [hunk 1]
```diff
@@ -197,7 +229,7 @@ public struct TargetSourcesBuilder {
         return Self.computeRule(for: path, toolsVersion: toolsVersion, rules: rules, declaredResources: [], declaredSources: nil, observabilityScope: observabilityScope)
     }
 
-    private static func computeRule(for path: AbsolutePath, toolsVersion: ToolsVersion, rules: [FileRuleDescription], declaredResources: [(path: AbsolutePath, rule: TargetDescription.Resource.Rule)], declaredSources: [AbsolutePath]?, observabilityScope: ObservabilityScope) -> FileRuleDescription.Rule {
+    private static func computeRule(for path: AbsolutePath, toolsVersion: ToolsVersion, rules: [FileRuleDescription], declaredResources: [(path: AbsolutePath, rule: TargetDescription.Resource.Rule)], declaredSources: [AbsolutePath]?, matchingResourceRuleHandler: (AbsolutePath) -> () = { _ in }, observabilityScope: ObservabilityScope) -> FileRuleDescription.Rule {
```
Comment (MaxDesiatov) [inline Sources/PackageLoading/TargetSourcesBuilder.swift:232]: line length nit

```suggestion
    private static func computeRule(
        for path: AbsolutePath, 
        toolsVersion: ToolsVersion,
        rules: [FileRuleDescription],
        declaredResources: [(path: AbsolutePath, rule: TargetDescription.Resource.Rule)],
        declaredSources: [AbsolutePath]?,
        matchingResourceRuleHandler: (AbsolutePath) -> () = { _ in },
        observabilityScope: ObservabilityScope
    ) -> FileRuleDescription.Rule {
```

**Review by MaxDesiatov — APPROVED** [review]

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test windows

**Comment by fwcd** [comment]
Hm, for some reason my package still won't generate a `Bundle.module` for out-of-tree resource paths... I'm using the most recent development toolchain:

```
Apple Swift version 5.11-dev (LLVM aaebcbf7670301b, Swift b96812513c64837)
Target: arm64-apple-macosx14.0
```
