### PR TITLE
Remove duplicate logs from `swift test` output

### LINKED ISSUE #9755: [Parity] Duplicate Swift Testing logs emitted  when using Swift Build build system
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [x] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

When using `swift test --build-system swiftbuild`, there are multiple duplicate logs emitted from Swift Testing.

### Expected behavior

```
❯ swift test --filter buildSystemOverrides --build-system swiftbuild --parallel
warning: 'swift-package-manager': failed to retrieve search paths with pkg-config; maybe pkg-config is not installed
warning: 'swift-package-manager': couldn't find pc file for sqlite3
Building for debugging...
[98/100] BinarySymbolsTests-product 278 / 280
[100/100] 
Build complete! (6.77 secs.)
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
◇ Suite BuildCommandTestCases started.
◇ Test buildSystemOverrides() started.
✔ Test buildSystemOverrides() passed after 3.663 seconds.
✔ Suite BuildCommandTestCases passed after 3.663 seconds.
✔ Test run with 1 test in 1 suite passed after 3.663 seconds.
```

### Actual behavior

```
❯ swift test --filter buildSystemOverrides --build-system swiftbuild --parallel
warning: 'swift-package-manager': failed to retrieve search paths with pkg-config; maybe pkg-config is not installed
warning: 'swift-package-manager': couldn't find pc file for sqlite3
Building for debugging...
[98/100] BinarySymbolsTests-product 278 / 280
[100/100] 
Build complete! (6.77 secs.)
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
◇ Suite BuildCommandTestCases started.
◇ Test buildSystemOverrides() started.
✔ Test buildSystemOverrides() passed after 3.663 seconds.
✔ Suite BuildCommandTestCases passed after 3.663 seconds.
✔ Test run with 1 test in 1 suite passed after 3.663 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
◇ Test run started.
↳ Testing Library Version: 6.4-dev (fd292629843b97d)
↳ Target Platform: arm64-apple-macosx
✔ Test run with 0 tests in 0 suites passed after 0.001 seconds.
```

### Steps to reproduce

1. Install a recent Swift toolchain, preferrably `main-snapshot`
2. Run the following:  ```
❯ cd <swift-package-manager>
❯ swift test --filter buildSystemOverrides --build-system swiftbuild
```


### Swift Package Manager version/commit hash

branch `main` at commit ID `2279d4e0745a3ce38e2790b82187df40303b6e49`

### Swift & OS version (output of `swift --version ; uname -a`)

OSS Swift toolchain `main-snapshot-2026-02-06` observed macOS, but unsure if this occurs on other platforms

### PR DESCRIPTION
**Pull request by bripeticca**
Fixes #9755 

When running swift tests either using the native build system or swiftbuild it's been noted that several test suite results would be recorded to the output even when there were 0 test cases run (upon using a `--filter`). 

Assure that if the test cases have been filtered that SwiftPM sends the appropriate list of test products to run against to the `TestRunner`, and avoid logging the results for these skipped tests/suites.

Added some methods to `TestingSupport` that will allow for SwiftPM to gather the Swift Testing test suites available, with some additional helpers that can filter these suites/their test cases depending on user-passed options. These are meant to mimic the behaviour we've implemented for XCTest test suites and their test cases such that we can pass the appropriate test product paths to be run, avoid unnecessary logs for test suites that ran no tests.

### CODE REVIEW

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci test windows

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci please test

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci test windows

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci test windows

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci test windows

**Comment by bripeticca** [comment]
@swift-ci test windows

File: Sources/Commands/SwiftTestCommand.swift [hunk 1]
```diff
@@ -371,9 +378,25 @@ public struct SwiftTestCommand: AsyncSwiftCommand {
...
+                    shouldSkipBuilding: options.sharedOptions.shouldSkipBuilding,
+                    sanitizers: globalOptions.build.sanitizers
+                )
+
+                // Filter test cases based on specifiers.
+                let tests = try testSuites
+                    .filteredTests(specifier: options.testCaseSpecifier)
+                    .skippedTests(specifier: options.skippedTests(fileSystem: swiftCommandState.fileSystem))
+
+                let filteredTestProducts = testProducts.filter { tests[$0.binaryPath] != nil }
```
Comment (plemarquand) [inline Sources/Commands/SwiftTestCommand.swift:394]: If we filter down to 0 can we just do `swiftCommandState.observabilityScope.emit(.noMatchingTests)` and return early?

File: Sources/Commands/Utilities/TestingSupport.swift [hunk 2]
```diff
@@ -159,6 +162,105 @@ enum TestingSupport {
         return try TestSuite.parse(jsonString: data, context: args.joined(separator: " "))
     }
 
+    static func getSwiftTestingSuites(
+        in testProducts: [BuiltTestProduct],
+        swiftCommandState: SwiftCommandState,
+        enableCodeCoverage: Bool,
```
Comment (plemarquand) [inline Sources/Commands/Utilities/TestingSupport.swift]: This is hardcoded to `false` in `Self.getSwiftTestingSuites`, we can just remove the argument.

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci test windows

**Comment by bripeticca** [comment]
@swift-ci test

**Comment by bripeticca** [comment]
@swift-ci test windows

**Comment by bripeticca** [comment]
@swift-ci test windows
