### PR TITLE
Use llvm-ar as default librarian on Unix platforms

### LINKED ISSUE #5761: SwiftPM requires librarian to be installed before it can build anything
### Description

This was introduced by #5720, which moved detecting the archiver executable from inside of llbuild to SPM. This has always been kind of a mess with SPM, with llbuild always grabbing whatever archiver was in the path. This didn't crop up much unless you were building the rare Swift package that had a static library and happened not to have a binutils package installed in your system.

However, [trunk SPM now won't build anything without an archiver included in the Swift toolchain or system path](https://github.com/buttaface/swift-android-sdk/runs/8225511990?check_suite_focus=true#step:6:6396), which is too strict. This is particularly an issue because the Swift toolchain doesn't ship with an archiver: I just checked when debugging this issue and was surprised to find that the official builds don't include `llvm-ar`.

The Swift compiler itself is much better on this issue, as [you can supply an alternate `-tools-directory` flag where it should look for an archiver, as done for Android](https://github.com/apple/swift/blob/main/docs/Android.md#2-compiling-helloswift-to-run-on-an-android-device). I just ran a variant of that compiler command and confirmed it uses the NDK llvm-ar:
```
> ./swift-5.6.3-RELEASE-ubuntu20.04/usr/bin/swiftc -tools-directory /home/butta/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin
-target aarch64-unknown-linux-android24 -sdk android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/sysroot
-resource-dir swift-5.6.3-android-aarch64-24-sdk/usr/lib/swift swift/test/Interpreter/Inputs/lto/module1.swift
-emit-library -static -v
...
/home/butta/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar crs libmodule1.a /tmp/TemporaryDirectory.yREHfG/module1-1.o
```
However, I see no flag to do the same with SPM, whereas [I could always pass the `-tools-directory` I want to SPM with the extra swiftc flags before](https://github.com/buttaface/swift-android-sdk/blob/45a56fcc752514b7521b6def4ba7a546c4a7c28e/android-aarch64.json#L11). With SPM itself checking for an archiver now, it errors before that compiler flag is ever used. I worked around this issue on my Android CI by [adding the NDK `llvm-ar` to my system path](https://github.com/buttaface/swift-android-sdk/commit/bcec0251beb986e6b57fcbb8fbd2fb44573af7b9#diff-76992bc322b65ab94f299c05ba3cbd8b3ab2e32ebfdde6db5adba70fa9f5a26aR68).

There are various ways to fix this: my preference would be to start shipping `llvm-ar` with the Swift toolchain and make that the default archiver we use.

### Expected behavior

Don't require `ar` or `llvm-ar` to be installed before building any Swift package, particularly since most won't use it.

### Actual behavior

`error: toolchain is invalid: could not find llvm-ar`

### Steps to reproduce

1. Make sure binutils is not installed.
2. Try to build any Swift package.

I realize that binutils is listed as a dependency of the Swift toolchain on linux, but when cross-compiling for other platforms and supplying your own archiver, as I'm doing for Android, it shouldn't be required that a system archiver be installed.   

### Swift Package Manager version/commit hash

Tested with the September 5 trunk snapshot

### Swift & OS version (output of `swift --version && uname -a`)

September 5 trunk snapshot running on Ubuntu 20.04 x86_64

### PR DESCRIPTION
**Pull request by finagolfin**
Resolves #5761

@compnerd, I implemented your TODO comment exactly.

### CODE REVIEW

File: Sources/PackageModel/UserToolchain.swift [hunk 1]
```diff
@@ -190,7 +188,18 @@ public final class UserToolchain: Toolchain {
...
             return librarian
         }
-        return try UserToolchain.findTool(tool, envSearchPaths: searchPaths, useXcrun: useXcrun)
+        if triple.isApple() || triple.isWindows {
+            return try UserToolchain.findTool(tool, envSearchPaths: searchPaths, useXcrun: useXcrun)
+        } else {
+            if let librarian = try? UserToolchain.findTool(tool, envSearchPaths: searchPaths, useXcrun: false) {
+                return librarian
+            }
+            // Fall back to looking for binutils `ar` if `llvm-ar` can't be found.
```
Comment (finagolfin) [inline Sources/PackageModel/UserToolchain.swift:197]: I don't think this fallback is necessary now that `llvm-ar` ships with all Swift toolchains, but I just followed the TODO comment I removed exactly for now.

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
Seems like a step in the right direction - @MaxDesiatov thoughts?

File: Sources/PackageModel/UserToolchain.swift (hunk 1 above)
Comment (neonichu) [reply Sources/PackageModel/UserToolchain.swift:197]: Which versions are we talking about? In theory, one can mix-and-match compilers and SwiftPM, so it would be unfortunate if we're cutting off versions that are recent.

Comment (neonichu) [reply Sources/PackageModel/UserToolchain.swift:197]: If we can support 5.8 and 5.9, that seems good enough, thanks.

**Comment by MaxDesiatov** [comment]
@swift-ci smoke test

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

File: Sources/PackageModel/UserToolchain.swift (hunk 1 above)
Comment (finagolfin) [reply Sources/PackageModel/UserToolchain.swift]: Removed the fallback as you suggested.

**Comment by compnerd** [comment]
Hmm, this doesn't fallback any longer?

**Comment by finagolfin** [comment]
> this doesn't fallback any longer?

Yes, I removed it based on Boris's suggestion, see the review comments above.

**Comment by finagolfin** [comment]
@egorzhdan, please run the CI on this.

**Comment by finagolfin** [comment]
@neonichu, another CI run and we can get this in?

**Comment by tomerd** [comment]
@swift-ci smoke test

**Comment by tomerd** [comment]
@MaxDesiatov @compnerd is this good to merge?

**Comment by compnerd** [comment]
I think that keeping the fallback is better.  The librarian is expected to be `ar`.  `llvm-ar` is a drop-in replacement, but the official archiver is still `ar` and we should resort to that if necessary.

**Comment by MaxDesiatov** [comment]
@swift-ci test windows

**Comment by MaxDesiatov** [comment]
IIRC @al45tair had a relevant change in this area, would be great to get his opinion

**Comment by finagolfin** [comment]
I don't think the fallback is necessary since the 5.8 toolchains onwards come with `llvm-ar`, so it just depends how safe you want to play it. @neonichu, wdyt?

The single self-hosted macOS test failure looks like a flake.

**Comment by neonichu** [comment]
> I don't think the fallback is necessary since the 5.8 toolchains onwards come with llvm-ar, so it just depends how safe you want to play it. @neonichu, wdyt?

I agree with you but @compnerd also makes a valid point. It might make new platform bringup easier to keep the fallback in place?

**Comment by finagolfin** [comment]
OK, I will put the fallback in again.

In the meantime, the macOS smoke test passed, meaning the self-hosted failure was a flake.

**Comment by finagolfin** [comment]
Rebased and the fallback is back.

**Comment by finagolfin** [comment]
One last CI run and we can get this in.

**Comment by egorzhdan** [comment]
@swift-ci please test

**Comment by finagolfin** [comment]
Hmm, only one CI ran?

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by finagolfin** [comment]
@compnerd, ready to go in, just needs approval.

**Comment by finagolfin** [comment]
@neonichu, can we get this in now?

**Review by neonichu — APPROVED** [review]

**Comment by finagolfin** [comment]
@neonichu, would be good to get this merged before the branch today.
