### PR TITLE
Skip compiling plugins when skipping building

### LINKED ISSUE #6683: `swift-test list --skip-build` builds SwiftPM plugins
When invoking `swift-test list --skip-build`, SwiftPM builds all plugins, even though it was explicitly requested that no build should be performed. This appears to be the cause of https://github.com/apple/sourcekit-lsp/issues/676.

Steps to reproduce.
1. `git clone https://github.com/adam-fowler/soto-codegenerator-plugin-test`
2. `/Library/Developer/Toolchains/swift-5.9-DEVELOPMENT-SNAPSHOT-2023-07-06-a.xctoolchain/usr/bin/swift-test list --skip-build`
3. Notice that we get log output about plugins being built and `ls .build/plugins/` contains build artifacts

### PR DESCRIPTION
**Pull request by neonichu**
Sink `shouldSkipBuilding` down into build parameters, so we can respect it whereever we would be trying to build, e.g. when trying to build plugins during build planning.

resolves #6683

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by rauhul** [comment]
Locally confirmed fixes #6673 (which I initially mis-diagnosed)

File: Sources/Build/BuildOperation.swift [hunk 1]
```diff
@@ -237,6 +237,9 @@ public final class BuildOperation: PackageStructureDelegate, SPMBuildCore.BuildS
 
     /// Perform a build using the given build description and subset.
     public func build(subset: BuildSubset) throws {
+        if buildParameters.shouldSkipBuilding {
+            return
+        }
```
Comment (MaxDesiatov) [inline Sources/Build/BuildOperation.swift:242]: nit: I'd expect this to use `guard` for early returns
```suggestion
        guard !buildParameters.shouldSkipBuilding else {
            return
        }
```

File: Sources/Commands/Utilities/TestingSupport.swift [hunk 2]
```diff
@@ -62,14 +62,15 @@ enum TestingSupport {
         throw InternalError("XCTestHelper binary not found, tried \(triedPaths.map { $0.pathString }.joined(separator: ", "))")
     }
 
-    static func getTestSuites(in testProducts: [BuiltTestProduct], swiftTool: SwiftTool, enableCodeCoverage: Bool, sanitizers: [Sanitizer]) throws -> [AbsolutePath: [TestSuite]] {
+    static func getTestSuites(in testProducts: [BuiltTestProduct], swiftTool: SwiftTool, enableCodeCoverage: Bool, shouldSkipBuilding: Bool, sanitizers: [Sanitizer]) throws -> [AbsolutePath: [TestSuite]] {
```
Comment (MaxDesiatov) [inline Sources/Commands/Utilities/TestingSupport.swift:65]: line length nit
```suggestion
    static func getTestSuites(
        in testProducts: [BuiltTestProduct], 
        swiftTool: SwiftTool, 
        enableCodeCoverage: Bool, 
        shouldSkipBuilding: Bool, 
        sanitizers: [Sanitizer]
    ) throws -> [AbsolutePath: [TestSuite]] {
```

**Review by MaxDesiatov — APPROVED** [review]
`if`/`guard` style and formatting nits, but otherwise LGTM

**Comment by MaxDesiatov** [comment]
I wonder if this can be tested?

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by neonichu** [comment]
@swift-ci please smoke test windows

**Comment by neonichu** [comment]
> I wonder if this can be tested?

It looks like we have an existing test for `--skip-build`, maybe we can beef that up to include a plugin as well.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@swift-ci please smoke test linux

**Review by tomerd — APPROVED** [review]
