### PR TITLE
Tests: Remove withKnownIssue in CoverageTests

### LINKED ISSUE #9588: [Parity][SwiftBuild] executing tests with coverage crashed on some platforms
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [x] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

Build tests tests with coverage, and then executing the tests without building causes a stack dump on some platforms

### Expected behavior

The coverage report is generated successfully

### Actual behavior

The following stack dump occurs

```
$ swift build --build-tests --enable-code-covera-build-system swiftbuild
Building for debugging...
Build description signature: d9a5814ed49bba048aaf54732bf91a2d3df4cdd80ff6a758fbc3f923ca0fb7df
Build description path: /workspaces/swift-package-manager/Fixtures/Miscellaneous/TestDiscovery/Simple/.build/out/Intermediates.noindex/XCBuildData/d9a5814ed49bba048aaf54732bf91a2d3df4cdd80ff6a758fbc3f923ca0fb7df.xcbuilddata
/workspaces/swift-package-manager/Fixtures/Miscellaneous/TestDiscovery/Simple/Package.swift: SimpleTests-test-runner: /usr/bin/ld.gold: warning: cannot find entry symbol 'bug_variant'
[100/100] SimpleTests-test-runner 58 / 58
[100/100] 
Build complete! (4.21 secs)


$ swift test --skip-build --enable-code-coverage --b
uild-system swiftbuild

*** Signal 4: Backtracing from 0xaaaab2260000... done ***

*** Program crashed: Illegal instruction at 0x0000aaaab2260000 ***

Platform: arm64 Linux (Ubuntu 22.04.5 LTS)

Thread 0 "SimpleTests-tes" crashed:

  0  0x0000aaaab2260000 <unknown> in SimpleTests-test-runner
...


Registers:

 x0 0x0000ffff9c6ab180  fd 7b b7 a9 a0 01 00 f0 00 00 01 91 fd 03 00 91  ý{·© ··ð····ý···
 x1 0x0000ffff9c6e3940  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
 x2 0x0000000000000000  0
 x3 0x0000ffffdc678fc8  60 a2 67 dc ff ff 00 00 c2 a2 67 dc ff ff 00 00  `¢gÜÿÿ··Â¢gÜÿÿ··
 x4 0x0000ffff9c6a52f0  70 33 6e 9c ff ff 00 00 00 b6 6d 9c ff ff 00 00  p3n·ÿÿ···¶m·ÿÿ··
 x5 0x0000ffff9a9a2c90  00 00 00 00 00 00 00 00 12 00 00 00 00 00 00 00  ················
 x6 0x0000000000000000  0
 x7 0x000602100b080000  1691117788069888
 x8 0x0000ffff9c696000  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
 x9 0x414d5f50565f4d56  4705521984323145046
x10 0x0000ffff9a804860  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
x11 0x0000000000000000  0
x12 0x000000000000000d  13
x13 0x0000000000000000  0
x14 0x2d67756265442f73  3271712719774166899
x15 0x0000000000000030  48
x16 0x0000aaaab2260000  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00  ·ELF············
x17 0x0000ffff9c690328  20 95 8e 9a ff ff 00 00 70 d4 83 9a ff ff 00 00   ···ÿÿ··pÔ··ÿÿ··
x18 0x0000000000000000  0
x19 0x0000000000000000  0
x20 0x0000000000000000  0
x21 0x0000aaaab2260000  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00  ·ELF············
x22 0x0000000000000000  0
x23 0x0000000000000000  0
x24 0x0000000000000000  0
x25 0x0000000000000000  0
x26 0x0000000000000000  0
x27 0x0000000000000000  0
x28 0x0000000000000000  0
 fp 0x0000000000000000  0
 lr 0x0000ffff9c6bdcc8  60 ff ff d0 00 00 06 91 f0 03 15 aa 00 02 1f d6  `ÿÿÐ····ð··ª···Ö
 sp 0x0000ffffdc678fb0  01 00 00 00 00 00 00 00 da a1 67 dc ff ff 00 00  ········Ú¡gÜÿÿ··
 pc 0x0000aaaab2260000  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00  ·ELF············


Images (24 omitted):

0x0000aaaab2260000–0x0000aaaab22b22b0 63b95e1e098c948234fdd41687bd2d7a2a4e8a90 SimpleTests-test-runner /workspaces/swift-package-manager/Fixtures/Miscellaneous/TestDiscovery/Simple/.build/out/Products/Debug-linux/SimpleTests-test-runner

Backtrace took 0.00s

error: Exited with unexpected signal code 4

*** Signal 4: Backtracing from 0xaaaaced80000... done ***

*** Program crashed: Illegal instruction at 0x0000aaaaced80000 ***

Platform: arm64 Linux (Ubuntu 22.04.5 LTS)

Thread 0 "SimpleTests-tes" crashed:

  0  0x0000aaaaced80000 <unknown> in SimpleTests-test-runner
...


Registers:

 x0 0x0000ffff9b1cb180  fd 7b b7 a9 a0 01 00 f0 00 00 01 91 fd 03 00 91  ý{·© ··ð····ý···
 x1 0x0000ffff9b203940  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
 x2 0x0000000000000000  0
 x3 0x0000ffffed82dfc8  59 f2 82 ed ff ff 00 00 bb f2 82 ed ff ff 00 00  Yò·íÿÿ··»ò·íÿÿ··
 x4 0x0000ffff9b1c52f0  70 33 20 9b ff ff 00 00 00 b6 1f 9b ff ff 00 00  p3 ·ÿÿ···¶··ÿÿ··
 x5 0x0000ffff994c2c90  00 00 00 00 00 00 00 00 12 00 00 00 00 00 00 00  ················
 x6 0x0000000000000000  0
 x7 0x00000602100b0800  6605928859648
 x8 0x0000ffff9b1b6000  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
 x9 0x414d5f50565f4d56  4705521984323145046
x10 0x0000ffff99324860  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
x11 0x0000000000000000  0
x12 0x0000000000000015  21
x13 0x0000000000000000  0
x14 0x632f78756e696c2d  7147063579419175981
x15 0x0000000000000038  56
x16 0x0000aaaaced80000  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00  ·ELF············
x17 0x0000ffff9b1b0328  20 95 40 99 ff ff 00 00 70 d4 35 99 ff ff 00 00   ·@·ÿÿ··pÔ5·ÿÿ··
x18 0x0000000000000000  0
x19 0x0000000000000000  0
x20 0x0000000000000000  0
x21 0x0000aaaaced80000  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00  ·ELF············
x22 0x0000000000000000  0
x23 0x0000000000000000  0
x24 0x0000000000000000  0
x25 0x0000000000000000  0
x26 0x0000000000000000  0
x27 0x0000000000000000  0
x28 0x0000000000000000  0
 fp 0x0000000000000000  0
 lr 0x0000ffff9b1ddcc8  60 ff ff d0 00 00 06 91 f0 03 15 aa 00 02 1f d6  `ÿÿÐ····ð··ª···Ö
 sp 0x0000ffffed82df80  07 00 00 00 00 00 00 00 75 f1 82 ed ff ff 00 00  ········uñ·íÿÿ··
 pc 0x0000aaaaced80000  7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00  ·ELF············


Images (24 omitted):

0x0000aaaaced80000–0x0000aaaacedd22b0 63b95e1e098c948234fdd41687bd2d7a2a4e8a90 SimpleTests-test-runner /workspaces/swift-package-manager/Fixtures/Miscellaneous/TestDiscovery/Simple/.build/out/Products/Debug-linux/SimpleTests-test-runner

Backtrace took 0.00s

error: Exited with unexpected signal code 4
```

### Steps to reproduce

1. clone `swift-package-manager` repository
2. `docker pull swiftlang/swift:nightly-main`
3. Open the repository with VSCode and start a Dev Container by rebuilding without the cache.
4. Run the following
    ```
    $ cd ./Fixtures/Miscellaneous/TestDiscovery/Simple/
    $ swift package clean
    $ swift build --build-tests --enable-code-covera-build-system swift build
    $ swift test --skip-build --enable-code-coverage --build-system swiftbuild
    ```

### Swift Package Manager version/commit hash

branch `main` at commit ID `c063612c78a316944618bc7e21f4bc86ba964ecd`

### Swift & OS version (output of `swift --version ; uname -a`)

Swift Toolchain version: `swift-DEVELOPMENT-SNAPSHOT-2026-01-09-a`

```
$ swift --version
Swift version 6.3-dev (LLVM d402ab9729f318e, Swift 2de856568572fc0)
Target: aarch64-unknown-linux-gnu
Build config: +assertions


$ uname -a
Linux 7ee3ae213571 6.6.9 #1 SMP Fri Sep  5 23:08:25 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by bkhouri**
All platform issues that were causing this test to fail have been fixed. Remove the `withKnownIssue` statement that was added in these tests.

Fixes: #9588
Issue: rdar://168006617

### CODE REVIEW

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
@swift-ci test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Review by owenv — APPROVED** [review]

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

File: Tests/IntegrationTests/SwiftPMTests.swift [hunk 1]
```diff
@@ -358,10 +360,10 @@ private struct SwiftPMTests {
                     #expect(binarySpecificProfrawFiles.count == 3)
                 }
             } when: {
-                [.linux, .windows].contains(ProcessInfo.hostOperatingSystem) && buildSystem == .swiftbuild
+                ProcessInfo.hostOperatingSystem == .linux && buildSystem == .swiftbuild
             }
         }
-        } when: {
+        } when : {
```
Comment (owenv) [inline Tests/IntegrationTests/SwiftPMTests.swift]: nit: accidental diff?

**Review by owenv — APPROVED** [review]

File: Tests/IntegrationTests/SwiftPMTests.swift (hunk 1 above)
Comment (bkhouri) [reply Tests/IntegrationTests/SwiftPMTests.swift]: It's accidental.  would you be ok if I leave this in as it doesn't impact the code, and I don't want to wait another round of CI builds?

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
@swift-ci test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
This PR fixes #9600
