### PR TITLE
SwiftBuild: add scratch path symbolic links

### LINKED ISSUE #9963: [Parity] Preserve .build/release and .build/debug symlinks in swiftbuild
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [x] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

`swiftbuild` does not preserve/create softlinks of current SPM behaviour of where the binaries are placed.

Instead a new build directory is used:
```
.build/out/Products
```

A softlink should be re-created so that `.build/release` -> `.build/out/Products/Release`, same step should be done for a debug build if built.

Current SPM behaviour is a softlink like:
```
debug -> arm64-apple-macosx/debug
```

[Searching GitHub](https://github.com/search?q=%22.build%2Frelease%22&type=code) for this pattern reveals that there are some 88 thousand references which will become invalid and this will break a massive amount of build/release scripts and documentation during migration.

### Expected behavior

Backward compatibility with the existing system.
`.build/debug` and `.build/release` symlinks to the build directory.

### Actual behavior

Binaries are only placed in `.build/out/Products`

### Steps to reproduce

_No response_

### Swift Package Manager version/commit hash

_No response_

### Swift & OS version (output of `swift --version ; uname -a`)

_No response_

### PR DESCRIPTION
**Pull request by bkhouri**
The native build system would create the `debug` and `release` symbolic link in the scratch path as they were the original output location before triple support was added.

Although this is not an officially support feature, add the `debug` and `release` symbolic links when using Swift Build to ease the transition until a better solution is avaiable.

Fixes: #9963
Issue: rdar://175144467

Merge with: https://github.com/swiftlang/sourcekit-lsp/pull/2620 (passed) or with https://github.com/swiftlang/sourcekit-lsp/pull/2621 (passed)

### CODE REVIEW

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
@swift-ci test

File: Sources/SwiftBuildSupport/SwiftBuildSystem.swift [hunk 1]
```diff
@@ -424,6 +430,35 @@ public final class SwiftBuildSystem: SPMBuildCore.BuildSystem {
         )
     }
 
+    func createBuildSymbolicLinks(
+        scrathPath: Basics.AbsolutePath,
```
Comment (owenv) [inline Sources/SwiftBuildSupport/SwiftBuildSystem.swift]:
```suggestion
        scratchPath: Basics.AbsolutePath,
```

File: Sources/SwiftBuildSupport/SwiftBuildSystem.swift [hunk 2]
```diff
@@ -424,6 +430,35 @@ public final class SwiftBuildSystem: SPMBuildCore.BuildSystem {
...
+        buildConfig: BuildConfiguration,
+    ) {
+        let oldBuildPath = scrathPath.appending(component: buildConfig.dirname)
+        if self.fileSystem.exists(oldBuildPath) {
+            do { try self.fileSystem.removeFileTree(oldBuildPath) }
```
Comment (owenv) [inline Sources/SwiftBuildSupport/SwiftBuildSystem.swift]: Might be worth a comment that this will not delete the build directory pointed to by the symlink, I had to lookup the docs to verify that

File: Sources/SwiftBuildSupport/SwiftBuildSystem.swift (hunk 1 above)
Comment (bkhouri) [reply Sources/SwiftBuildSupport/SwiftBuildSystem.swift]: Nice catch.

File: Sources/SwiftBuildSupport/SwiftBuildSystem.swift (hunk 2 above)
Comment (bkhouri) [reply Sources/SwiftBuildSupport/SwiftBuildSystem.swift]: comment added.

**Comment by bkhouri** [comment]
https://github.com/swiftlang/sourcekit-lsp/pull/2616

@swift-ci test

**Comment by bkhouri** [comment]
https://github.com/swiftlang/sourcekit-lsp/pull/2616

@swift-ci test windows

**Comment by dschaefer2** [comment]
My first thought is that it would be nice to do this outside the build system. Show bin path works right from the command state and you have everything you need there. It's just looks awkward having to pass in the scratch path directory all the way down just to create the link.

But that's more a code cleanliness thing.

**Comment by dschaefer2** [comment]
That said buildSystem.build is called from all over the place in SwiftPM so that may be hard to do.

File: Sources/SwiftBuildSupport/SwiftBuildSystem.swift [hunk 3]
```diff
@@ -424,6 +430,38 @@ public final class SwiftBuildSystem: SPMBuildCore.BuildSystem {
         )
     }
 
+    func createBuildSymbolicLinks(
+        scratchPath: Basics.AbsolutePath,
+        buildConfig: BuildConfiguration,
+    ) {
+        let oldBuildPath = scratchPath.appending(component: buildConfig.dirname)
+        if self.fileSystem.exists(oldBuildPath) {
```
Comment (plemarquand) [inline Sources/SwiftBuildSupport/SwiftBuildSystem.swift]: use `exists(oldBuildPath, followSymlink: false)`. 

If `.build/debug` points to a symlink target that no longer exists, `exists` will return false even though the symlink is there and now dangling pointing at nothing. If this symlinks remains dangling, this code never cleans it up and it stays around forever.

File: Sources/SwiftBuildSupport/SwiftBuildSystem.swift [hunk 4]
```diff
@@ -406,6 +406,12 @@ public final class SwiftBuildSystem: SPMBuildCore.BuildSystem {
             replArguments: nil,
         )
 
+        defer {
+            createBuildSymbolicLinks(
```
Comment (plemarquand) [inline Sources/SwiftBuildSupport/SwiftBuildSystem.swift]: We should guard so this only gets written if target path exists (i.e. the build got far enough along to write it). If the build fails immediately we'll be left with a dangling symlink.

**Review by plemarquand — CHANGES_REQUESTED** [review]
Can you add some tests to validate this new behaviour?

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Comment by bkhouri** [comment]
@swift-ci test

**Comment by bkhouri** [comment]
@swift-ci test windows

**Review by plemarquand — APPROVED** [review]

**Comment by bkhouri** [comment]
https://github.com/swiftlang/sourcekit-lsp/pull/2620

@swift-ci test

**Comment by bkhouri** [comment]
https://github.com/swiftlang/sourcekit-lsp/pull/2621

@swift-ci test

**Review by dschaefer2 — APPROVED** [review]
