### PR TITLE
Mark plugin-only dependencies in required targets as required

### LINKED ISSUE #4334: Package resolution fails when a dependency uses an SPM-plugin for code generation
### Expected behavior
Compilation should complete as if the dependency wasn't using an SPM-plugin for code generation.

### Actual behavior
Package resolution fails with

```
product 'SmokeFrameworkGenerateHttp1' required by package 'emptyexampleservice' target 'EmptyExampleOperationsHTTP1' not found in package 'smoke-framework-application-generate'.
```

### Steps to reproduce

1. Use SPM to create a new package.
2. Clone the `smoke-framework-examples` repository locally.
3. Add the `EmptyExampleService` as a local dependency [1]
4. Try to resolve the dependencies, it should fail with the error

[1] `.package(path: "${BASE_PATH}/smoke-framework-examples/EmptyExampleService"),`

### If possible, minimal yet complete reproducer code (or URL to code)

_[anything to help us reproducing the issue]_

### Swift Package Manager version/commit hash

5.6.1

### Swift & OS version (output of `swift --version && uname -a`)
swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: x86_64-apple-macosx12.0
Darwin 3c22fb28ce76.ant.amazon.com 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by neonichu**
In tools-version 5.2 or higher, we only include dependencies which are required in the package graph. Historically, any dependencies required by a target that's included in a product was considered required, we also need to include any dependencies that vend plugins required by those targets.

fixes #4334
rdar://93982305

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please smoke test

File: Sources/PackageModel/Manifest.swift [hunk 1]
```diff
@@ -307,6 +313,20 @@ public final class Manifest {
 
         return packageDependency(referencedBy: packageName)
     }
+
+    /// Finds the package dependency referenced by the specified plugin usage.
+    /// - Returns: Returns `nil` if  the used plugin is from the same package or if the package the used plugin is from cannot be found.
+    public func packageDependency(
+        referencedBy pluginUsage: TargetDescription.PluginUsage) -> PackageDependency? {
+        switch pluginUsage {
+        case .plugin(_, let package):
```
Comment (tomerd) [inline Sources/PackageModel/Manifest.swift:322]: nit: can use `Some(package)` to eliminate the `if let package = package` dance, or map  on the optional if you prefer

**Comment by neonichu** [comment]
```
Test Suite 'Selected tests' started at 2022-07-11 21:37:33.135Test Suite 'PluginTests' started at 2022-07-11 21:37:33.137Test Case 'PluginTests.testTransitivePluginOnlyDependency' started at 2022-07-11 21:37:33.137/home/build-user/swiftpm/Tests/FunctionalTests/PluginTests.swift:909: error: PluginTests.testTransitivePluginOnlyDependency : XCTAssertTrue failed - stdout:
Compiling plugin MyPlugin...
Building for debugging...
[1/1] Compiling Library Library.swift
[2/2] Merging module Library
[3/3] Compiling TransitivePluginOnlyDependency TransitivePluginOnlyDependency.swift
[4/4] Merging module TransitivePluginOnlyDependency
Build complete! (1.73s)Test Case 'PluginTests.testTransitivePluginOnlyDependency' 
```

Looks like the output of `swift build` looks slightly different on Linux, I'll update the test.

**Comment by neonichu** [comment]
@swift-ci please smoke test

**Comment by tomerd** [comment]
@neonichu do we need a 5.7 version of this PR?

**Comment by neonichu** [comment]
> @neonichu do we need a 5.7 version of this PR?

Yep, it's on my list to open one.
